import { GachaItem } from '../types/index.js';

/* constants */
export const character: GachaItem[] = [
  {
    name: 'ホタル',
    id: 'sr_firefly',
    game: 'starrail',
    emoji: '<:firefly:1281220375816048640>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'トパーズ',
    id: 'sr_topaz',
    game: 'starrail',
    emoji: '<:topaz:1281220764657520660>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '旅人',
    id: 'ys_traveler',
    game: 'genshin',
    emoji: '<:traveler:1274587625205927996>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ナヒーダ',
    id: 'ys_nahida',
    game: 'genshin',
    emoji: '<:nahida:1278193309528887357>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'クリーパー',
    id: 'minecraft:creeper',
    game: 'minecraft',
    emoji: '<:creeper:1274591880796967022>',
    weight: 0.05,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ガスト',
    id: 'minecraft:ghast',
    game: 'minecraft',
    emoji: '<:ghast:1274599765304152087>',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: 'ヒツジ',
    id: 'minecraft:sheep',
    game: 'minecraft',
    weight: 0.08,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ネコ',
    id: 'minecraft:cat',
    game: 'minecraft',
    weight: 0.04,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'エンダーマン',
    id: 'minecraft:enderman',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'rare',
    },
  },
  {
    name: 'ブタ',
    id: 'minecraft:pig',
    game: 'minecraft',
    weight: 0.08,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ニワトリ',
    id: 'minecraft:chicken',
    game: 'minecraft',
    weight: 0.08,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ウシ',
    id: 'minecraft:cow',
    game: 'minecraft',
    weight: 0.08,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'スケルトン',
    id: 'minecraft:skeleton',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'uncommon',
    },
  },
  {
    name: 'ゾンビ',
    id: 'minecraft:zombie',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'クモ',
    id: 'minecraft:spider',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ウィザー',
    id: 'minecraft:wither',
    game: 'minecraft',
    weight: 0.001,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: 'エンダードラゴン',
    id: 'minecraft:ender_dragon',
    game: 'minecraft',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: 'ピグリン',
    id: 'minecraft:piglin',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ピグリン ブルート',
    id: 'minecraft:piglin_brute',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ゾンビ ピグリン(ピッグマン)',
    id: 'minecraft:zombie_pigman',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '雷電将軍',
    id: 'ys_raiden_shogun',
    game: 'starrail',
    emoji: '<:raiden_shogun:1278192548292329553>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'アベンチュリン',
    id: 'sr_aventurine',
    game: 'starrail',
    emoji: '<:aventurine:1281217134302597172>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ヘルタ',
    id: 'sr_herta',
    game: 'starrail',
    emoji: '<:herta:1281217420324765761>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '姫子',
    id: 'sr_himeko',
    game: 'starrail',
    emoji: '<:himeko:1281217857677561886>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ゼーレ',
    id: 'sr_seele',
    game: 'starrail',
    emoji: '<:seele:1281218187890790401>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'クラーラ',
    id: 'sr_clara',
    game: 'starrail',
    emoji: '<:clara:1281218375955255378>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ジェパード',
    id: 'sr_gepard',
    game: 'starrail',
    emoji: '<:gepard:1281218644818530379>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ブローニャ',
    id: 'sr_bronya',
    game: 'starrail',
    emoji: '<:bronya:1281218786774749308>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '景元',
    id: 'sr_jing_yuan',
    game: 'starrail',
    emoji: '<:jing_yuan:1281219012939874315>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '鏡流',
    id: 'sr_kei_ryu',
    game: 'starrail',
    emoji: '<:kei_ryu:1281219275973197824>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '花火',
    id: 'sr_sparkle',
    game: 'starrail',
    emoji: '<:sparkle:1281219486816538644>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ブラックスワン',
    id: 'sr_blackswan',
    game: 'starrail',
    emoji: '<:blackswan:1281219740991492179>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ロビン',
    id: 'sr_robin',
    game: 'starrail',
    emoji: '<:robin:1281219851733438505>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '銀狼',
    id: 'sr_silverwolf',
    game: 'starrail',
    emoji: '<:silverwolf:1281219963155251291>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '刃',
    id: 'sr_blade',
    game: 'starrail',
    emoji: '<:blade:1281220249718358068>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '黄泉',
    id: 'sr_acheron',
    game: 'starrail',
    emoji: '<:acheron:1281221467882786928>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ブートヒル',
    id: 'sr_boothill',
    game: 'starrail',
    emoji: '<:boothill:1281221692458274836>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
];

export const item: GachaItem[] = [
  {
    name: 'ダイヤモンドの剣',
    id: 'minecraft:diamond_sword',
    game: 'minecraft',
    emoji: '<:diamond_sword:1274585426258296863>',
    weight: 0.008,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: 'ネザライトの剣',
    id: 'minecraft:netherite_sword',
    game: 'minecraft',
    emoji: '<:netherite_sword:1274585591358685245>',
    weight: 0.002,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: '調理済みの豚肉',
    id: 'minecraft:cooked_porkchop',
    game: 'minecraft',
    emoji: '<:porkchop_cooked:1274585754869436507>',
    weight: 0.12,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '調理済みの羊肉',
    id: 'minecraft:cooked_mutton',
    game: 'minecraft',
    emoji: '<:mutton_cooked:1274585714415370271>',
    weight: 0.12,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '石',
    id: 'minecraft:stone',
    game: 'minecraft',
    emoji: '<:stone:1274623206908760064>',
    weight: 0.08,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '鉄のインゴット',
    id: 'minecraft:iron_ingot',
    game: 'minecraft',
    emoji: '<:iron_ingot:1274623595397513330>',
    weight: 0.06,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'uncommon',
    },
  },
  {
    name: '金のインゴット',
    id: 'minecraft:gold_ingot',
    game: 'minecraft',
    emoji: '<:gold_ingot:1274623833097244733>',
    weight: 0.05,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'uncommon',
    },
  },
  {
    name: 'ダイヤモンド',
    id: 'minecraft:diamond',
    game: 'minecraft',
    emoji: '<:diamond:1274623999938400296>',
    weight: 0.04,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'rare',
    },
  },
  {
    name: 'ネザライトインゴット',
    id: 'minecraft:netherite_ingot',
    game: 'minecraft',
    emoji: '<:netherite_ingot:1274625317197053984>',
    weight: 0.008,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'rare',
    },
  },
  {
    name: 'サトウキビ',
    id: 'minecraft:sugar_cane',
    game: 'minecraft',
    emoji: '<:reeds:1274625835403313233>',
    weight: 0.1,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'レッドストーン',
    id: 'minecraft:redstone_dust',
    game: 'minecraft',
    emoji: '<:redstone_dust:1274626139062796288>',
    weight: 0.06,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ラピスラズリ',
    id: 'minecraft:lapis_lazuli',
    game: 'minecraft',
    emoji: '<:lapis_lazuli:1274626522065539123>',
    weight: 0.06,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ネザースター',
    id: 'minecraft:nether_star',
    game: 'minecraft',
    emoji: '<:nether_star:1274626824667795606>',
    weight: 0.008,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: '金のリンゴ',
    id: 'minecraft:apple_golden',
    game: 'minecraft',
    emoji: '<:apple_golden:1274627027063803924>',
    weight: 0.05,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'rare',
    },
  },
  {
    name: 'エンチャントされた金のリンゴ',
    id: 'minecraft:enchanted_golden_apple',
    game: 'minecraft',
    emoji: '<:enchanted_golden_apple:1274629665780142121>',
    weight: 0.008,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: 'オークの原木',
    id: 'minecraft:oak_log',
    game: 'minecraft',
    emoji: '<:log_oak:1274630435372007509>',
    weight: 0.14,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '草ブロック',
    id: 'minecraft:grass_block',
    game: 'minecraft',
    emoji: '<:grass_block:1274632892911321130>',
    weight: 0.13,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '土',
    id: 'minecraft:dirt',
    game: 'minecraft',
    emoji: '<:dirt:1274633849950703636>',
    weight: 0.16,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'Common',
    id: 'sol_common',
    game: 'sol',
    weight: 0.3,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 2',
    },
  },
  {
    name: 'Rage : Heated',
    id: 'sol_rage_heated',
    game: 'sol',
    weight: 0.000078125,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 12800',
    },
  },
  {
    name: 'Jackpot',
    id: 'sol_jackpot',
    game: 'sol',
    emoji: ':coin:',
    weight: 0.0012870012870013,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 777',
    },
  },
  {
    name: 'Flushed',
    id: 'sol_flushed',
    game: 'sol',
    emoji: ':flushed:',
    weight: 0.0001449275362318841,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 6900',
    },
  },
  {
    name: 'Powered',
    id: 'sol_powered',
    game: 'sol',
    weight: 0.00006103515625,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 16384',
    },
  },
  {
    name: 'Lunar',
    id: 'sol_lunar',
    game: 'sol',
    weight: 0.00002,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 50000',
    },
  },
  {
    name: 'ジャンボ宝くじ1等',
    id: 'custom_takarakuji',
    game: 'other',
    emoji: '<:takarakuji:1278190917995462748>',
    weight: 0.00000005,
    type: 'item',
    rarity: {
      type: 'other',
      rarity: '1 in 10000000',
    },
  },
  {
    name: 'キャラクターガチャチケット',
    id: 'ticket_character',
    game: 'other',
    emoji: ':tickets:',
    weight: 0.07,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'mythic',
    },
  },
  {
    name: 'キャラクターガチャチケット 10枚',
    id: 'ticket_character',
    count: 10,
    hidden: true,
    game: 'other',
    emoji: ':tickets:',
    weight: 0.004,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'mythic',
    },
  },
  {
    name: 'キャラクターガチャチケット 50枚',
    id: 'ticket_character',
    count: 50,
    hidden: true,
    game: 'other',
    emoji: ':tickets:',
    weight: 0.00015,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'mythic',
    },
  },
  {
    name: 'キャラクターガチャチケット 100枚',
    id: 'ticket_character',
    count: 100,
    hidden: true,
    game: 'other',
    emoji: ':tickets:',
    weight: 0.00008,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'mythic',
    },
  },
  {
    name: 'コンバットアサルトライフル',
    id: 'fn_combat_assault_rifle',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'アサルトライフル',
    id: 'fn_assault_rifle',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'タクティカル ショットガン',
    id: 'fn_tactical_shotgun',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'ヘビー スナイパーライフル',
    id: 'fn_heavy_sniper_rifle',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'カメックの光線銃',
    id: 'fn_ray_gun',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'ポンプショットガン',
    id: 'fn_pump_shotgun',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'ヘビーショットガン',
    id: 'fn_heavy_shotgun',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'サブマシンガン',
    id: 'fn_submachine_gun',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'ピストル',
    id: 'fn_pistol',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'ゾンビの集団',
    id: 'minecraft:zombie',
    game: 'minecraft',
    weight: 0.01,
    count: 6,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'rare',
    },
  },
];

export const _translation = {
  rarity: {
    common: 'コモン',
    uncommon: 'アンコモン',
    rare: 'レア',
    epic: 'エピック',
    legendary: 'レジェンダリー',
    mythic: 'ミシック',
    1: '⭐',
    2: '⭐⭐',
    3: '⭐⭐⭐',
    4: '⭐⭐⭐⭐',
    5: '⭐⭐⭐⭐⭐',
  },
  game: {
    starrail: '崩壊: スターレイル',
    genshin: '原神',
    minecraft: 'マインクラフト',
    sol: "Sol's RNG",
    othello: '逆転オセロニア',
    other: 'その他',
    fortnite: 'Fortnite',
  },
};
