import { GachaItem } from '../types/index.js';

/* constants */
export const character: GachaItem[] = [
  {
    name: '[花束の魔女]ナターシャ',
    id: 'mm_natasha_2nd',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: '【弔花の魔女】ナターシャ',
    id: 'mm_natasha',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'プリマヴェーラ',
    id: 'mm_primavera',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'アムレート',
    id: 'mm_amleth',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ソルティーナ',
    id: 'mm_soltina',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'マーリン',
    id: 'mm_merlyn',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'コルディ',
    id: 'mm_cordie',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'コルディ(浴衣)',
    id: 'mm_cordie_yukata',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'フローレンス',
    id: 'mm_florence',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'メルティーユ',
    id: 'mm_mertillier',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ロザリー',
    id: 'mm_rosalie',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'R',
    },
  },
  {
    name: 'アイリス',
    id: 'mm_iris',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'R',
    },
  },
  {
    name: 'チェルナ',
    id: 'mm_cherna',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'R',
    },
  },
  {
    name: 'ニーナ',
    id: 'mm_nina',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ソーニャ',
    id: 'mm_sonya',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'モーザ',
    id: 'mm_moddey',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ソテイラ',
    id: 'mm_soteira',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'フィアー',
    id: 'mm_fia',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'イリア',
    id: 'mm_illya',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'A.A.',
    id: 'mm_aa',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'カグヤ',
    id: 'mm_kaguya',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'パラデア',
    id: 'mm_paladea',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'イリア (神呪)',
    id: 'mm_illiya_god_curse',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'アームストロング',
    id: 'mm_armstrong',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'オフィーリア',
    id: 'mm_ophelia',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ルナリンド',
    id: 'mm_lunalynn',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ロザリー(使徒)',
    id: 'mm_rosalie_apostle',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'メリア',
    id: 'mm_meria',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'エルフリンデ',
    id: 'mm_elfriede',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ルサールカ',
    id: 'mm_rusalka',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ケルベロス',
    id: 'mm_cerberus',

    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'フォルティナ',
    id: 'mm_fortina',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'アイネ',
    id: 'mm_aine',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'モーザ (水着)',
    id: 'mm_moddey_swimsuit',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'アイリス (黒鎧)',
    id: 'mm_iris_tainted',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'アモール',
    id: 'mm_amour',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'アモール (聖夜)',
    id: 'mm_amour_holy_night',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'アムレート (夏)',
    id: 'mm_amuleth_summer',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'トロポン',
    id: 'mm_tropon',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'リシェス',
    id: 'mm_richesse',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'オリヴィエ',
    id: 'mm_olivia',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ミミ',
    id: 'mm_mimi',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ハトホル',
    id: 'mm_hathor',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'カロル',
    id: 'mm_carol',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'アサヒ',
    id: 'mm_asahi',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'スクルド',
    id: 'mm_skuld',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'サブリナ',
    id: 'mm_subrina',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'サブリナ (水着)',
    id: 'mm_subrina_swimsuit',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'セルリア',
    id: 'mm_serruria',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ルーク',
    id: 'mm_luke',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'レア',
    id: 'mm_lea',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'アイビー',
    id: 'mm_ivy',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'クラウディア',
    id: 'mm_claudia',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'アレクサンドラ',
    id: 'mm_alexandra',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ザラ',
    id: 'mm_zara',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'R',
    },
  },
  {
    name: 'リブラ',
    id: 'mm_libra',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'R',
    },
  },
  {
    name: 'シズ',
    id: 'mm_shizu',
    game: 'mementomori',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'N',
    },
  },
  {
    name: 'ソフィア',
    id: 'mm_sophia',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'プリシラ',
    id: 'mm_priscilla',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'フレイシア',
    id: 'mm_freesia',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'R',
    },
  },
  {
    name: 'ディアン',
    id: 'mm_dian',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'R',
    },
  },
  {
    name: 'ベル',
    id: 'mm_belle',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'テオドラ',
    id: 'mm_theodora',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'R',
    },
  },
  {
    name: 'ペトラ',
    id: 'mm_petra',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'R',
    },
  },
  {
    name: 'アリアンロッド',
    id: 'mm_arianrhod',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'R',
    },
  },
  {
    name: 'ニーナ (夏)',
    id: 'mm_nina_summer',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: 'ステラ',
    id: 'mm_stella',
    game: 'mementomori',
    weight: 0.003,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
  {
    name: '【冠菊】花海 咲季',
    id: 'gakumasu_saki_kamurogiku',
    game: 'gakumasu',
    weight: 0.001,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'SSR',
    },
  },
  {
    name: '【アイヴイ】月村 手毬',
    id: 'gakumasu_temari_ivy',
    game: 'gakumasu',
    weight: 0.001,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'SSR',
    },
  },
  {
    name: '【Luna say maybe】月村 手毬',
    id: 'gakumasu_temari_lunasaymaybe',
    game: 'gakumasu',
    weight: 0.001,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'SSR',
    },
  },
  {
    name: '【一匹狼】月村 手毬',
    id: 'gakumasu_temari_wolf',
    game: 'gakumasu',
    weight: 0.005,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'SR',
    },
  },
  {
    name: '【仮装狂騒曲】月村 手毬',
    id: 'gakumasu_temari_halloween',
    game: 'gakumasu',
    weight: 0.001,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'SSR',
    },
  },
  {
    name: '【冠菊】葛城 リーリヤ',
    id: 'gakumasu_ririya_kamurogiku',
    game: 'gakumasu',
    weight: 0.001,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'SSR',
    },
  },
  {
    name: '【初】花海 咲季',
    id: 'gakumasu_saki_hajime',
    game: 'gakumasu',
    weight: 0.001,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'R',
    },
  },
  {
    name: '【Fighting my way】花海 咲季',
    id: 'gakumasu_saki_fightingmyway',
    game: 'gakumasu',
    weight: 0.001,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'SSR',
    },
  },
  {
    name: '【初】藤田 ことね',
    id: 'gakumasu_kotone_hajime',
    game: 'gakumasu',
    weight: 0.01,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'R',
    },
  },
  {
    name: '【世界一可愛い私】藤田 ことね',
    id: 'gakumasu_kotone_sekai1kawaiiwatashi',
    game: 'gakumasu',
    weight: 0.001,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'SSR',
    },
  },
  {
    name: '【初】月村 手毬',
    id: 'gakumasu_temari_hajime',
    game: 'gakumasu',
    weight: 0.01,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'R',
    },
  },
  {
    name: '【初】葛城 リーリヤ',
    id: 'gakumasu_ririya_hajime',
    game: 'gakumasu',
    weight: 0.01,
    type: 'character',
    rarity: {
      type: 'gakumasu',
      rarity: 'R',
    },
  },
  {
    name: 'ホタル',
    id: 'sr_firefly',
    game: 'starrail',
    emoji: '<:firefly:1281220375816048640>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'トパーズ',
    id: 'sr_topaz',
    game: 'starrail',
    emoji: '<:topaz:1281220764657520660>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'リサ',
    id: 'ys_lisa',
    game: 'genshin',
    weight: 0.005,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '行秋',
    id: 'ys_xingqiu',
    game: 'genshin',
    weight: 0.005,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '旅人',
    id: 'ys_traveler',
    game: 'genshin',
    emoji: '<:traveler:1274587625205927996>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ナヒーダ',
    id: 'ys_nahida',
    game: 'genshin',
    emoji: '<:nahida:1278193309528887357>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ダインスレイヴ',
    id: 'ys_dainsleif',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 7,
    },
  },
  {
    name: 'キィニチ',
    id: 'ys_kinich',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '綺良々',
    id: 'ys_kirara',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'クレー',
    id: 'ys_klee',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ヌヴィレット',
    id: 'ys_neuvillette',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ナヴィア',
    id: 'ys_navia',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ムアラニ',
    id: 'ys_mualani',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'レイラ',
    id: 'ys_layla',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'リネット',
    id: 'ys_lynette',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'リネ',
    id: 'ys_lyney',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'モナ',
    id: 'ys_mona',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '七七',
    id: 'ys_qiqi',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ノエル',
    id: 'ys_noelle',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'ロサリア',
    id: 'ys_rosaria',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'シグウィン',
    id: 'ys_sigewinne',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'スクロース',
    id: 'ys_sucrose',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '「公子」タルタリヤ',
    id: 'ys_tartaglia',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '放浪者',
    id: 'ys_wanderer',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '「召使」アルレッキーノ',
    id: 'ys_arlecchino',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'バーバラ',
    id: 'ys_barbara',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'フレミネ',
    id: 'ys_freminet',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'ゴロー',
    id: 'ys_gorou',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'アルハイゼン',
    id: 'ys_alhaitham',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ベネット',
    id: 'ys_bennett',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '重雲',
    id: 'ys_chongyun',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'シャルロット',
    id: 'ys_charlotte',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'シュヴルーズ',
    id: 'ys_chervreuse',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'クロリンデ',
    id: 'ys_clorinde',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'コレイ',
    id: 'ys_collei',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'セノ',
    id: 'ys_cyno',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ディシア',
    id: 'ys_dehya',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ディルック',
    id: 'ys_diluc',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ドリー',
    id: 'ys_dori',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'カチーナ',
    id: 'ys_kachina',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '胡桃',
    id: 'ys_hu_tao',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '楓原万葉',
    id: 'ys_kaedehara_kazuha',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ジン',
    id: 'ys_jean',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ティナリ',
    id: 'ys_tighnari',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ウェンティ',
    id: 'ys_venti',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ヨォーヨ',
    id: 'ys_yaoyao',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'アンバー',
    id: 'ys_amber',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '甘雨',
    id: 'ys_ganyu',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '白朮',
    id: 'ys_baizhu',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '嘉明',
    id: 'ys_gaming',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '千織',
    id: 'ys_chiyori',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '魈',
    id: 'ys_xiao',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '八重神子',
    id: 'ys_yae_miko',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '香菱',
    id: 'ys_xiangling',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'トーマ',
    id: 'ys_thoma',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '久岐忍',
    id: 'ys_kuki_shinobu',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '珊瑚宮心海',
    id: 'ys_sangonomiya_kokomi',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '申鶴',
    id: 'ys_shenhe',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '鹿野院平蔵',
    id: 'ys_shikanoin_heizou',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'アルベド',
    id: 'ys_albedo',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ファルザン',
    id: 'ys_faruzan',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'フィッシュル',
    id: 'ys_fischl',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'ニィロウ',
    id: 'ys_nilou',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '刻晴',
    id: 'ys_keqing',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'カーヴェ',
    id: 'ys_kaveh',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: 'キャサリン',
    id: 'ys_katheryne',
    game: 'genshin',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 7,
    },
  },
  {
    name: 'リオセスリ',
    id: 'ys_wriothesley',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'フリーナ',
    id: 'ys_furina',
    game: 'genshin',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ガイア',
    id: 'ys_kaeya',
    game: 'genshin',
    weight: 0.004,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '鍾離',
    id: 'ys_zhongli',
    game: 'genshin',
    weight: 0.004,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '雲菫',
    id: 'ys_yun_jin',
    game: 'genshin',
    weight: 0.004,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },

  {
    name: '宵宮',
    id: 'ys_yoimiya',
    game: 'genshin',
    weight: 0.004,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '夜蘭',
    id: 'ys_yelan',
    game: 'genshin',
    weight: 0.004,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'アレイ',
    id: 'minecraft:allay',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'クリーパー',
    id: 'minecraft:creeper',
    game: 'minecraft',
    emoji: '<:creeper:1274591880796967022>',
    weight: 0.05,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ガスト',
    id: 'minecraft:ghast',
    game: 'minecraft',
    emoji: '<:ghast:1274599765304152087>',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: 'ヒツジ',
    id: 'minecraft:sheep',
    game: 'minecraft',
    weight: 0.08,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ネコ',
    id: 'minecraft:cat',
    game: 'minecraft',
    weight: 0.04,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'エンダーマン',
    id: 'minecraft:enderman',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'rare',
    },
  },
  {
    name: '襲撃者',
    id: 'minecraft:pillager',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ブタ',
    id: 'minecraft:pig',
    game: 'minecraft',
    weight: 0.08,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ニワトリ',
    id: 'minecraft:chicken',
    game: 'minecraft',
    weight: 0.08,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ウシ',
    id: 'minecraft:cow',
    game: 'minecraft',
    weight: 0.07,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'スケルトン',
    id: 'minecraft:skeleton',
    game: 'minecraft',
    weight: 0.04,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'uncommon',
    },
  },
  {
    name: 'ゾンビ',
    id: 'minecraft:zombie',
    game: 'minecraft',
    weight: 0.05,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'クモ',
    id: 'minecraft:spider',
    game: 'minecraft',
    weight: 0.04,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ウィザー',
    id: 'minecraft:wither',
    game: 'minecraft',
    weight: 0.0012,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: 'エンダードラゴン',
    id: 'minecraft:ender_dragon',
    game: 'minecraft',
    weight: 0.0035,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: 'ピグリン',
    id: 'minecraft:piglin',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ピグリン ブルート',
    id: 'minecraft:piglin_brute',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'シルバーフィッシュ',
    id: 'minecraft:silverfish',
    game: 'minecraft',
    weight: 0.07,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ウォーデン',
    id: 'minecraft:warden',
    game: 'minecraft',
    weight: 0.0012,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ゾンビ ピグリン(ピッグマン)',
    id: 'minecraft:zombie_pigman',
    game: 'minecraft',
    weight: 0.02,
    type: 'character',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '雷電将軍',
    id: 'ys_raiden_shogun',
    game: 'genshin',
    emoji: '<:raiden_shogun:1278192548292329553>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'アベンチュリン',
    id: 'sr_aventurine',
    game: 'starrail',
    emoji: '<:aventurine:1281217134302597172>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ヘルタ',
    id: 'sr_herta',
    game: 'starrail',
    emoji: '<:herta:1281217420324765761>',
    weight: 0.002,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 4,
    },
  },
  {
    name: '姫子',
    id: 'sr_himeko',
    game: 'starrail',
    emoji: '<:himeko:1281217857677561886>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ゼーレ',
    id: 'sr_seele',
    game: 'starrail',
    emoji: '<:seele:1281218187890790401>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'クラーラ',
    id: 'sr_clara',
    game: 'starrail',
    emoji: '<:clara:1281218375955255378>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ジェパード',
    id: 'sr_gepard',
    game: 'starrail',
    emoji: '<:gepard:1281218644818530379>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ブローニャ',
    id: 'sr_bronya',
    game: 'starrail',
    emoji: '<:bronya:1281218786774749308>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '景元',
    id: 'sr_jing_yuan',
    game: 'starrail',
    emoji: '<:jing_yuan:1281219012939874315>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '鏡流',
    id: 'sr_kei_ryu',
    game: 'starrail',
    emoji: '<:kei_ryu:1281219275973197824>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '花火',
    id: 'sr_sparkle',
    game: 'starrail',
    emoji: '<:sparkle:1281219486816538644>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ブラックスワン',
    id: 'sr_blackswan',
    game: 'starrail',
    emoji: '<:blackswan:1281219740991492179>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ロビン',
    id: 'sr_robin',
    game: 'starrail',
    emoji: '<:robin:1281219851733438505>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '銀狼',
    id: 'sr_silverwolf',
    game: 'starrail',
    emoji: '<:silverwolf:1281219963155251291>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '刃',
    id: 'sr_blade',
    game: 'starrail',
    emoji: '<:blade:1281220249718358068>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: '黄泉',
    id: 'sr_acheron',
    game: 'starrail',
    emoji: '<:acheron:1281221467882786928>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ブートヒル',
    id: 'sr_boothill',
    game: 'starrail',
    emoji: '<:boothill:1281221692458274836>',
    weight: 0.0016,
    type: 'character',
    rarity: {
      type: 'ys',
      rarity: 5,
    },
  },
  {
    name: 'ナターシャ',
    id: 'sr_natasha',
    game: 'starrail',
    weight: 0.001092,
    type: 'character',
    rarity: {
      type: 'mementomori',
      rarity: 'SR',
    },
  },
];

export const item: GachaItem[] = [
  {
    name: 'ダイヤモンドの剣',
    id: 'minecraft:diamond_sword',
    game: 'minecraft',
    emoji: '<:diamond_sword:1274585426258296863>',
    weight: 0.008,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: 'ネザライトの剣',
    id: 'minecraft:netherite_sword',
    game: 'minecraft',
    emoji: '<:netherite_sword:1274585591358685245>',
    weight: 0.002,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: '調理済みの豚肉',
    id: 'minecraft:cooked_porkchop',
    game: 'minecraft',
    emoji: '<:porkchop_cooked:1274585754869436507>',
    weight: 0.12,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '調理済みの羊肉',
    id: 'minecraft:cooked_mutton',
    game: 'minecraft',
    emoji: '<:mutton_cooked:1274585714415370271>',
    weight: 0.12,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '石',
    id: 'minecraft:stone',
    game: 'minecraft',
    emoji: '<:stone:1274623206908760064>',
    weight: 0.08,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '鉄のインゴット',
    id: 'minecraft:iron_ingot',
    game: 'minecraft',
    emoji: '<:iron_ingot:1274623595397513330>',
    weight: 0.06,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'uncommon',
    },
  },
  {
    name: '金のインゴット',
    id: 'minecraft:gold_ingot',
    game: 'minecraft',
    emoji: '<:gold_ingot:1274623833097244733>',
    weight: 0.05,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'uncommon',
    },
  },
  {
    name: 'ダイヤモンド',
    id: 'minecraft:diamond',
    game: 'minecraft',
    emoji: '<:diamond:1274623999938400296>',
    weight: 0.04,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'rare',
    },
  },
  {
    name: 'ネザライトインゴット',
    id: 'minecraft:netherite_ingot',
    game: 'minecraft',
    emoji: '<:netherite_ingot:1274625317197053984>',
    weight: 0.008,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'rare',
    },
  },
  {
    name: 'サトウキビ',
    id: 'minecraft:sugar_cane',
    game: 'minecraft',
    emoji: '<:reeds:1274625835403313233>',
    weight: 0.1,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'レッドストーン',
    id: 'minecraft:redstone_dust',
    game: 'minecraft',
    emoji: '<:redstone_dust:1274626139062796288>',
    weight: 0.06,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ラピスラズリ',
    id: 'minecraft:lapis_lazuli',
    game: 'minecraft',
    emoji: '<:lapis_lazuli:1274626522065539123>',
    weight: 0.06,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'ネザースター',
    id: 'minecraft:nether_star',
    game: 'minecraft',
    emoji: '<:nether_star:1274626824667795606>',
    weight: 0.008,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: '金のリンゴ',
    id: 'minecraft:apple_golden',
    game: 'minecraft',
    emoji: '<:apple_golden:1274627027063803924>',
    weight: 0.05,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'rare',
    },
  },
  {
    name: 'エンチャントされた金のリンゴ',
    id: 'minecraft:enchanted_golden_apple',
    game: 'minecraft',
    emoji: '<:enchanted_golden_apple:1274629665780142121>',
    weight: 0.008,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'epic',
    },
  },
  {
    name: 'オークの原木',
    id: 'minecraft:oak_log',
    game: 'minecraft',
    emoji: '<:log_oak:1274630435372007509>',
    weight: 0.14,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '草ブロック',
    id: 'minecraft:grass_block',
    game: 'minecraft',
    emoji: '<:grass_block:1274632892911321130>',
    weight: 0.13,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: '土',
    id: 'minecraft:dirt',
    game: 'minecraft',
    emoji: '<:dirt:1274633849950703636>',
    weight: 0.16,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'common',
    },
  },
  {
    name: 'Common',
    id: 'sol_common',
    game: 'sol',
    weight: 0.3,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 2',
    },
  },
  {
    name: 'Rage : Heated',
    id: 'sol_rage_heated',
    game: 'sol',
    weight: 0.000078125,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 12800',
    },
  },
  {
    name: 'Jackpot',
    id: 'sol_jackpot',
    game: 'sol',
    emoji: ':coin:',
    weight: 0.0012870012870013,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 777',
    },
  },
  {
    name: 'Flushed',
    id: 'sol_flushed',
    game: 'sol',
    emoji: ':flushed:',
    weight: 0.0001449275362318841,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 6900',
    },
  },
  {
    name: 'Powered',
    id: 'sol_powered',
    game: 'sol',
    weight: 0.00006103515625,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 16384',
    },
  },
  {
    name: 'Lunar',
    id: 'sol_lunar',
    game: 'sol',
    weight: 0.00002,
    type: 'item',
    rarity: {
      type: 'sol',
      rarity: '1 in 50000',
    },
  },
  {
    name: 'ジャンボ宝くじ1等',
    id: 'custom_takarakuji',
    game: 'other',
    emoji: '<:takarakuji:1278190917995462748>',
    weight: 0.00000005,
    type: 'item',
    rarity: {
      type: 'other',
      rarity: '1 in 10000000',
    },
  },
  {
    name: 'キャラクターガチャチケット',
    id: 'ticket_character',
    game: 'other',
    emoji: ':tickets:',
    weight: 0.07,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'mythic',
    },
  },
  {
    name: 'キャラクターガチャチケット 10枚',
    id: 'ticket_character',
    count: 10,
    hidden: true,
    game: 'other',
    emoji: ':tickets:',
    weight: 0.004,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'mythic',
    },
  },
  {
    name: 'キャラクターガチャチケット 50枚',
    id: 'ticket_character',
    count: 50,
    hidden: true,
    game: 'other',
    emoji: ':tickets:',
    weight: 0.00015,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'mythic',
    },
  },
  {
    name: 'キャラクターガチャチケット 100枚',
    id: 'ticket_character',
    count: 100,
    hidden: true,
    game: 'other',
    emoji: ':tickets:',
    weight: 0.00008,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'mythic',
    },
  },
  {
    name: '潜在宝珠（1時間）',
    id: 'mm_senzaihouju1',
    game: 'mementomori',
    weight: 0.003,
    type: 'item',
    rarity: {
      type: 'mementomori',
      rarity: 'SSR',
    },
  },
  {
    name: '潜在宝珠（2時間）',
    id: 'mm_senzaihouju2',
    game: 'mementomori',
    weight: 0.003,
    type: 'item',
    rarity: {
      type: 'mementomori',
      rarity: 'SSR',
    },
  },
  {
    name: '潜在宝珠（4時間）',
    id: 'mm_senzaihouju4',
    game: 'mementomori',
    weight: 0.003,
    type: 'item',
    rarity: {
      type: 'mementomori',
      rarity: 'SSR',
    },
  },
  {
    name: '潜在宝珠（6時間）',
    id: 'mm_senzaihouju6',
    game: 'mementomori',
    weight: 0.003,
    type: 'item',
    rarity: {
      type: 'mementomori',
      rarity: 'SSR',
    },
  },
  {
    name: '潜在宝珠（8時間）',
    id: 'mm_senzaihouju8',
    game: 'mementomori',
    weight: 0.003,
    type: 'item',
    rarity: {
      type: 'mementomori',
      rarity: 'SSR',
    },
  },
  {
    name: '潜在宝珠（24時間）',
    id: 'mm_senzaihouju24',
    game: 'mementomori',
    weight: 0.003,
    type: 'item',
    rarity: {
      type: 'mementomori',
      rarity: 'SSR',
    },
  },
  {
    name: 'コンバットアサルトライフル',
    id: 'fn_combat_assault_rifle',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'アサルトライフル',
    id: 'fn_assault_rifle',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'タクティカル ショットガン',
    id: 'fn_tactical_shotgun',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'ヘビー スナイパーライフル',
    id: 'fn_heavy_sniper_rifle',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'カメックの光線銃',
    id: 'fn_ray_gun',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'ポンプショットガン',
    id: 'fn_pump_shotgun',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'ヘビーショットガン',
    id: 'fn_heavy_shotgun',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'サブマシンガン',
    id: 'fn_submachine_gun',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'ピストル',
    id: 'fn_pistol',
    game: 'fortnite',
    weight: 0.01,
    type: 'item',
    rarity: {
      type: 'fn',
      rarity: 'legendary',
    },
  },
  {
    name: 'ゾンビの集団',
    id: 'minecraft:zombie',
    game: 'minecraft',
    weight: 0.01,
    count: 6,
    type: 'item',
    rarity: {
      type: 'mc',
      rarity: 'rare',
    },
  },
];

export const _translation = {
  rarity: {
    common: 'コモン',
    uncommon: 'アンコモン',
    rare: 'レア',
    epic: 'エピック',
    legendary: 'レジェンダリー',
    mythic: 'ミシック',
    1: '⭐',
    2: '⭐⭐',
    3: '⭐⭐⭐',
    4: '⭐⭐⭐⭐',
    5: '⭐⭐⭐⭐⭐',
    6: '⭐⭐⭐⭐⭐⭐',
    7: '不明',
  },
  game: {
    starrail: '崩壊: スターレイル',
    genshin: '原神',
    minecraft: 'マインクラフト',
    sol: "Sol's RNG",
    othello: '逆転オセロニア',
    other: 'その他',
    fortnite: 'Fortnite',
    gakumasu: '学園アイドルマスター',
    zenless: 'Zenless Zone Zero',
    mementomori: 'メメントモリ',
  },
};
